# config.yml

#backend:
#  name: git-gateway
#  branch: main # Branch to update (optional; defaults to master)
backend:
  name: github
  repo: alonrotem/jekyll-self-build # Path to your GitHub repository
  # optional, defaults to master
  branch: work
  base_url: "https://salmon-xerus-tutu.cyclic.app/"

media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }